name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use custom edit file action
        run: |
          sed -i '/plugins {/a\    id("org.cyclonedx.bom") version "1.8.2"' "build.gradle.kts"
          sed -i '/^$/a\ tasks.named<Jar>("bootJar") {\ dependsOn(tasks.named("cyclonedxBom"))\ from(file("$buildDir/reports")) {\ include("application.cdx.json")\ into("META-INF/sbom")\ }\ }\ \ tasks.named<Jar>("jar") {\ dependsOn(tasks.named("cyclonedxBom"))\ from(file("$buildDir/reports")) {\ include("application.cdx.json")\ into("META-INF/sbom")\ }\ }\ \ tasks.cyclonedxBom {\ outputName.set("application.cdx")\ outputFormat.set("json")\ schemaVersion.set("1.5")\ destination.set(file("build/reports"))\ includeConfigs.set(listOf("runtimeClasspath", "compileClasspath"))\ skipConfigs.set(emptyList())\ skipProjects.set(emptyList())\ }' "build.gradle.kts"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew build
